### PR TITLE
Convert library to real functions

### PR DESCRIPTION
**Pull request by DenisCarriere**
- Code linting using [Javascript Standard Style](http://standardjs.com/)
- Convert library to "real" functions (Source code is still ES5, which is compatible with Internet Explorer 9)
- Added [JSDocs to functions](http://documentation.js.org/) will help for documentation and help define Typescript definitions

### CODE REVIEW

**Comment by MartyWallace** [comment]
The only concern I have with altering the original source is that if the original author releases a new version, it will be a lot of work to replicate what you've done here to that new release. Totally up to you if you're cool to do that. I'll add you as a collaborator now anyway and you can decide.

**Comment by DenisCarriere** [comment]
👍 Well there's a lot of Javascript mistakes in his original source code, ideally the original author should work on one repo... why is he contributing to his own private repo?

I don't mind editing the changes if the author pushes new commits.

**Comment by MartyWallace** [comment]
Basically it's a very old project that I wanted to use in a project with Bower, so I picked it up from there whacked it as-is into GitHub and then submitted it to bower 😊

**Comment by DenisCarriere** [comment]
@MartyWallace we want to include `PolyK` as a dependency in `TurfJS`.

Guidelines for dependencies:
- Compatible with ES5
- MIT license
- Hosted on `npm`

You can check out the module announcement (https://github.com/Turfjs/turf/issues/580).

I'll remove any GeoJSON reference to `PolyK` and keep it as native as possible.

So far, none of the behavior has changed, it still acts the same way as before.

👍 I'll be submitting a few more changes in the next few hours.

**Comment by MartyWallace** [comment]
It almost seems like you would achieve your needs more cleanly by just extracting the functionality of PolyK and dropping it into a new node module using the style you prefer. If we deviate too much, it will make the [original documentation](http://polyk.ivank.net/?p=documentation) invalid. What do you think?

**Comment by DenisCarriere** [comment]
@MartyWallace Yea we can do that, so far nothing has change in your documentation, just cleaning up the library.

I'll try to only do minor changes to the `index.js`.

**Comment by DenisCarriere** [comment]
@MartyWallace 👍 I'll make sure none of the functionality changes, so far it's the same.

**Pull request merged**
